[tool.poetry]
name = "yi-game-agent"
version = "0.1.0"
description = ""
authors = ["Yimi81 <1548222878@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
llama-index = "^0.11.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
